# Generated by Django 5.2.3 on 2025-10-31 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('coureses', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('goals', models.CharField(blank=True, max_length=100)),
                ('stu_year', models.DateField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_colab.module')),
            ],
        ),
        migrations.CreateModel(
            name='stu_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_colab.module')),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_initiated', to='student_colab.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_received', to='student_colab.student')),
            ],
        ),
    ]
