# Generated by Django 5.2.7 on 2025-10-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_colab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='coureses',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='module',
        ),
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(blank=True, to='student_colab.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
