# Generated by Django 5.2.7 on 2025-11-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_colab', '0002_rename_coureses_student_course_remove_student_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
